language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shanvel26/docker-react -f Dockerfile.dev .

#script: 
#  - docker run -e CI=true shanvel26/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-728007737632"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

